Added note on method-style named scopes
To elaborate

```ruby
class User < ActiveRecord::Base

  def User.old
    where('age > ?', 80)
  end

  def User.heavy
    where('weight > ?', 200)
  end

end
```

then in usage

```
> User.old.heavy
NoMethodError: undefined method `heavy' for #<ActiveRecord::Relation:0x0000000acfabe8>
```
Conflicts:
	README.md